### ISSUE TITLE
Show value inside 'thing'

### ISSUE THREAD

**Issue by flatsiedatsie** [tsathishkumar/MySController-rs#26]
I don't know if this is a MySController-rs or Mozilla Gateway issue. But I noticed that in the things overview all the devices created with MySController-rs just say 'thing' in the middle of them. While picture by Mozilla show that devices can also directly show their most relevant value in the middle of them.

Currently I have to click on a device to see its value.

This might be a reason not to merge devices into more complex versions, since then you will always need to click on them to see all the values they represent. I wonder how Mozilla is planning to handle this.

**Comment by freaktechnik** [comment]
To have a value displayed inside a thing you need to implement one of the capabilities: https://mozilla-iot.github.io/schemas/

Currently there aren't any fitting capabilities for weather stations or similar, though you may get acceptable results with https://mozilla-iot.github.io/schemas/#MultiLevelSensor since humidity can be represented as a LevelProperty (even if that's not totally correct).

**Comment by flatsiedatsie** [comment]
Could this be something to include in this project?

**Comment by tsathishkumar** [comment]
That would be in webthing-rust crate.

**Comment by flatsiedatsie** [comment]
This is now probably covered by
https://github.com/tsathishkumar/MySController-rs/issues/24
